### ISSUE TITLE
Error installing the package

### ISSUE THREAD

**Issue by pooja19862** [wuaipinglab/ImmuCC#1]
Hello Dr. Chen,

Thanks for great package. I tried installing it by using following code , but it gave errors devtools::install_github("chenziyi/ImmuCC")

Error : Installation failed: Does not appear to be an R package (no DESCRIPTION)

**Comment by chenziyi** [comment]
Dear Shah,

Thanks for your interests in our research work. The scripts listed in the github is an executable file which you can run directly without the installation.

Best regards!





在 2017-06-29 01:06:05，"pooja19862" <notifications@github.com> 写道：


Hello Dr. Chen,

Thanks for great package. I tried installing it by using following code , but it gave errors devtools::install_github("chenziyi/ImmuCC")

Error : Installation failed: Does not appear to be an R package (no DESCRIPTION)

**Comment by kate-simonova** [comment]
I also cant install this pakage.

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

```
