### ISSUE TITLE
Maximum size of input file

### ISSUE THREAD

**Issue by Ezshik** [wuaipinglab/ImmuCC#3]
Hello Dr. Chen,

Thank you for the ImmuCC package and web-server - I need it so much for my current work!

The issue is that when I use the web-server, I get errors for input matrix with more than 2 columns (number of rows is 45987). So, I wonder if there is a limit for the size of input file?

Thank you,
Andrey

**Comment by chenziyi** [comment]
Thank you for your interest in our research work. Please send the expression matrix to me if you don not mind it. My email address: chziy429@163.com

**Comment by chenziyi** [comment]
Thank you for your interest in our research work. Please send the expression matrix to me if you don not mind it. My email address: chziy429@163.com

**Comment by Ezshik** [comment]
Dear Dr. Chen,

Thank you for your willingness to help!

I have clarified the issue: it looks like one additional empty row at the end of expression matrix led to error.

Best,
Andrey
