### ISSUE TITLE
Websever not online

### ISSUE THREAD

**Issue by SteveBoothHLI** [wuaipinglab/ImmuCC#5]
Hi there, the webserver is no longer online at any of the posted addresses:
http://218.4.234.74:3200/immune/
http://wap-lab.org:3200/immune/

Is there a new URL that we can use?
Thanks!
Steve

**Comment by chenziyi** [comment]
Hi,


The website works well in our institute. Maybe the website were restricted by your institute. Please connect with the web administer in your institute for more detail and send me the potential problem.



Best



在 2019-03-09 03:12:05，"SteveBoothHLI" <notifications@github.com> 写道：


Hi there, the webserver is no longer online at any of the posted addresses:
http://218.4.234.74:3200/immune/
http://wap-lab.org:3200/immune/

Is there a new URL that we can use?
Thanks!
Steve

**Comment by SteveBoothHLI** [comment]
Hi there, you are completely correct. My institute is blocking the site for some reason. 

I will close the issue.
Thanks and best, 
Steve
