### ISSUE TITLE
Mouse lung expression

### ISSUE THREAD

**Issue by SteveBoothHLI** [wuaipinglab/ImmuCC#6]
Hi there, I have microarray data from mouse lungs. Is it better for me to deconvolute using the full 'srep40508-s1.csv' signature matrix, or should I use the lung specific  'Lung.sig.matrix.csv' found here?:
https://github.com/wuaipinglab/ImmuCC/tree/master/tissue_Immucc/SignatureMatrix

Best,
Steve

**Comment by chenziyi** [comment]
Dear prof Steve,


The Lung.sig.matrix.csv' was constructed based on single cell sequencing data and was developed for RNA-Seq data but not for microarray data, so there are still a few points that limited its application on your data.

Best


Please send your information with email but not reply it on Github



Best


在 2019-03-13 02:46:36，"SteveBoothHLI" <notifications@github.com> 写道：


Hi there, I have microarray data from mouse lungs. Is it better for me to deconvolute using the full 'srep40508-s1.csv' signature matrix, or should I use the lung specific 'Lung.sig.matrix.csv' found here?:
https://github.com/wuaipinglab/ImmuCC/tree/master/tissue_Immucc/SignatureMatrix

Best,
Steve
