### ISSUE TITLE
Can ImmuCC be used with unstranded RNA-seq data?

### ISSUE THREAD

**Issue by btoe** [wuaipinglab/ImmuCC#8]
Hi, I noticed in the RNA-seq data processing pipeline that there is step where you determine the strandness information. However, the RNA-seq data I have is unstranded. I was wondering if I can still apply ImmuCC on an RNA-seq dataset that is unstranded.

Thank you!

**Comment by chenziyi** [comment]
The strandness information estimated here will be used in latter quantification steps. Sometimes, people may not know this information for their own datasets or some public datasets. Therefore, this step was added to extract this information from the mapping data("*.bam"). However, you can ignore this step if you are sure for your data and just use it in latter quantification steps. Also, you can run your data according to the pipeline we provided. It will have no impact on your result.
